export const MERCHANT_KEYWORD_RULES: Record<string, string[]> = {
  "Fast Food": [
    "MCDONALD",
    "TIM HORTONS",
    "WENDY",
    "BURGER KING",
    "A&W",
    "KFC",
    "POPEYES",
    "SUBWAY",
    "HARVEY",
    "TACO BELL",
  ],
  "Food Delivery": [
    "UBER EATS",
    "DOORDASH",
    "SKIPTHEDISHES",
    "SKIP THE DISHES",
  ],
  Coffee: ["STARBUCKS", "TIM HORTONS", "SECOND CUP"],
  Groceries: [
    "FORTINOS",
    "NO FRILLS",
    "WALMART",
    "COSTCO",
    "FOOD BASICS",
    "METRO",
    "SOBEYS",
    "LONGOS",
    "FRESHCO",
    "LOBLAWS",
    "REAL CANADIAN SUPERSTORE",
  ],
  Subscriptions: [
    "NETFLIX",
    "SPOTIFY",
    "APPLE.COM/BILL",
    "GOOGLE",
    "MICROSOFT",
    "ADOBE",
    "AMAZON PRIME",
    "OPENAI",
    "ANTHROPIC",
    "CHATGPT",
  ],
  Transportation: ["UBER", "LYFT", "PRESTO", "GO TRANSIT"],
  Gas: ["SHELL", "ESSO", "PETRO", "PIONEER", "CIRCLE K"],
  Shopping: [
    "AMAZON",
    "BEST BUY",
    "WINNERS",
    "MARSHALLS",
    "SPORT CHEK",
    "UNIQLO",
    "ZARA",
    "H&M",
  ],
  Transfers: [
    "E-TRANSFER",
    "TRANSFER",
    "ONLINE BANKING TRANSFER",
    "PAYMENT",
    "BILL PAYMENT",
    "CREDIT CARD PAYMENT",
  ],
};

export const SUBSCRIPTION_KEYWORDS = MERCHANT_KEYWORD_RULES.Subscriptions;

export const TRANSFER_KEYWORDS = MERCHANT_KEYWORD_RULES.Transfers;
