export const MERCHANT_KEYWORD_RULES: Record<string, string[]> = {
  "Fast Food": [
    "MCDONALD",
    "TIM HORTONS",
    "WENDY",
    "BURGER KING",
    "A&W",
    "KFC",
    "POPEYES",
    "SUBWAY",
    "HARVEY",
    "TACO BELL",
  ],
  "Food Delivery": [
    "UBER EATS",
    "DOORDASH",
    "SKIPTHEDISHES",
    "SKIP THE DISHES",
  ],
  Coffee: ["STARBUCKS", "TIM HORTONS", "SECOND CUP"],
  Groceries: [
    "FORTINOS",
    "NO FRILLS",
    "WALMART",
    "COSTCO",
    "FOOD BASICS",
    "METRO",
    "SOBEYS",
    "LONGOS",
    "FRESHCO",
    "LOBLAWS",
    "REAL CANADIAN SUPERSTORE",
  ],
  Subscriptions: [
    "NETFLIX",
    "SPOTIFY",
    "APPLE.COM/BILL",
    "GOOGLE",
    "MICROSOFT",
    "ADOBE",
    "AMAZON PRIME",
    "OPENAI",
    "ANTHROPIC",
    "CHATGPT",
    "STEAM",
    "PLAYSTATION",
    "SONY INTERACTIV",
    "XBOX",
    "SUPERCELL",
    "NINTENDO",
    "DISNEY PLUS",
    "CRUNCHYROLL",
    "YOUTUBE",
    "ICLOUD",
    "DROPBOX",
    "GITHUB",
    "LINKEDIN",
  ],
  Entertainment: [
    "STEAM",
    "PLAYSTATION",
    "XBOX",
    "NINTENDO",
    "CINEPLEX",
    "FAMOUS PLAYER",
  ],
  Transportation: ["UBER", "LYFT", "PRESTO", "GO TRANSIT"],
  Gas: ["SHELL", "ESSO", "PETRO", "PIONEER", "CIRCLE K"],
  Shopping: [
    "AMAZON",
    "BEST BUY",
    "WINNERS",
    "MARSHALLS",
    "SPORT CHEK",
    "UNIQLO",
    "ZARA",
    "H&M",
  ],
  Transfers: [
    "E-TRANSFER",
    "TRANSFER",
    "ONLINE BANKING TRANSFER",
    "BILL PAYMENT",
    "CREDIT CARD PAYMENT",
    "PAYMENT - THANK YOU",
    "PAYMENT THANK YOU",
    "WEALTHSIMPLE",
    "QUESTRADE",
    "QTRADE",
    "TD WATERHOUSE",
    "DIRECT INVEST",
    "RBC INVEST",
    "INVESTMENT PURCHASE",
    "RRSP",
    "TFSA",
    "FHSA",
    "MACKENZIE",
    "VANGUARD",
  ],
};

export const INCOME_KEYWORDS = [
  "PAYROLL",
  "PAYROLL DEPOSIT",
  "DIRECT DEPOSIT",
  "DEPOSIT",
  "EFT DEPOSIT",
  "SALARY",
  "WAGE",
  "PAY CHEQUE",
  "PAYCHEQUE",
  "PAY CHEQ",
  "EMPLOYER",
  "PAYMENT FROM",
  "GOVT OF",
  "GOVERNMENT OF",
  "SERVICE CANADA",
  "EI PAYMENT",
  "INTERAC E-TRANSFER RECEIVED",
  "E-TRANSFER RECEIVED",
  "AUTOMATIC DEPOSIT",
  "MOBILE DEPOSIT",
];

export const SUBSCRIPTION_KEYWORDS = MERCHANT_KEYWORD_RULES.Subscriptions;

export const TRANSFER_KEYWORDS = MERCHANT_KEYWORD_RULES.Transfers;
