/** Ordered rules — first match wins (most specific categories first). */
export const CATEGORY_KEYWORD_RULES: { category: string; keywords: string[] }[] =
  [
    {
      category: "Subscriptions",
      keywords: [
        "APPLE COM BILL",
        "APPLE.COM/BILL",
        "APPLECOMBILL",
        "APPLE BILL",
        "ITUNES",
        "ICLOUD",
        "NETFLIX",
        "SPOTIFY",
        "DISNEY PLUS",
        "DISNEYPLUS",
        "HBO MAX",
        "PRIME VIDEO",
        "AMAZON PRIME",
        "YOUTUBE PREMIUM",
        "YOUTUBE MUSIC",
        "GOOGLE ONE",
        "GOOGLE STORAGE",
        "MICROSOFT 365",
        "OFFICE 365",
        "ADOBE",
        "OPENAI",
        "CHATGPT",
        "ANTHROPIC",
        "CLAUDE AI",
        "GITHUB",
        "LINKEDIN PREMIUM",
        "DROPBOX",
        "CRUNCHYROLL",
        "DAZN",
        "PARAMOUNT",
        "PEACOCK",
        "HULU",
        "AUDIBLE",
        "KINDLE UNLTD",
        "XBOX GAME PASS",
        "PLAYSTATION PLUS",
        "NINTENDO SWITCH ONLINE",
        "STEAM PURCHASE",
        "SUPERCELL",
        "PATREON",
        "SUBSTACK",
        "ONLYFANS",
        "CANVA",
        "NOTION",
        "SLACK",
        "ZOOM",
        "GRAMMARLY",
        "LASTPASS",
        "1PASSWORD",
        "NORDVPN",
        "EXPRESSVPN",
        "TELUS MOBILITY",
        "ROGERS WIRELESS",
        "BELL MOBILITY",
        "FIDO",
        "KOODO",
        "VIRGIN PLUS",
        "CHATR",
        "PUBLIC MOBILE",
      ],
    },
    {
      category: "Alcohol & Beverages",
      keywords: [
        "LCBO",
        "BEER STORE",
        "WINE RACK",
        "SAQ ",
        "SAQ-",
        "LIQUOR",
        "SPIRITS",
        "WINERY",
        "BREWERY",
        "TAPS AND TANKARD",
        "WINE SHOP",
      ],
    },
    {
      category: "Transfers",
      keywords: [
        "E-TRANSFER",
        "INTERAC E TRANSFER",
        "ONLINE BANKING TRANSFER",
        "BILL PAYMENT",
        "CREDIT CARD PAYMENT",
        "PAYMENT - THANK YOU",
        "PAYMENT THANK YOU",
        "WEALTHSIMPLE",
        "QUESTRADE",
        "QTRADE",
        "TD WATERHOUSE",
        "DIRECT INVEST",
        "RBC INVEST",
        "INVESTMENT PURCHASE",
        "RRSP",
        "TFSA",
        "FHSA",
        "MACKENZIE",
        "VANGUARD",
        "TRANSFER TO",
        "TRANSFER FROM",
        "ATM WITHDRAWAL",
        "CASH ADVANCE",
      ],
    },
    {
      category: "Fast Food & Delivery",
      keywords: [
        "MCDONALD",
        "MCDONALDS",
        "TIM HORTONS",
        "TIMHORTONS",
        "WENDY",
        "WENDYS",
        "BURGER KING",
        "A&W",
        "KFC",
        "POPEYES",
        "SUBWAY",
        "HARVEY",
        "HARVEYS",
        "TACO BELL",
        "FIREHOUSE SUB",
        "FIREHOUSE SUBS",
        "QUIZNOS",
        "JIMMY JOHN",
        "FIVE GUYS",
        "SHAKE SHACK",
        "IN-N-OUT",
        "CHIPOTLE",
        "QDOBA",
        "PANDA EXPRESS",
        "LITTLE CAESARS",
        "DOMINOS",
        "DOMINO'S",
        "PIZZA PIZZA",
        "PIZZA HUT",
        "PAPA JOHN",
        "MARY BROWN",
        "NEW YORK FRIES",
        "A&W REST",
        "SWISS CHALET",
        "ST HUBERT",
        "ST-HUBERT",
        "KELSEYS",
        "MONTANA",
        "UBER EATS",
        "DOORDASH",
        "SKIPTHEDISHES",
        "SKIP THE DISHES",
        "SKIPTHEDIS",
        "RITUAL",
        "FANTUAN",
        "PCEXPRESS",
        "INSTACART",
        "DOLLARAMA FOOD",
        "DRIVE THRU",
        "DRIVE-THRU",
      ],
    },
    {
      category: "Coffee",
      keywords: [
        "STARBUCKS",
        "SECOND CUP",
        "TIM HORTONS COFF",
        "COFFEE TIME",
        "COFFEE TIME DONUTS",
        "BRIGIL COFFEE",
        "BRIGIL",
        "ARABICA",
        "ESPRESSO",
        "DUNKIN",
        "COFFEE BEAN",
        "BRUU",
        "PILOT COFFEE",
        "Aroma Espresso",
        "AROMA ESPRESSO",
      ],
    },
    {
      category: "Restaurants",
      keywords: [
        "SUNSET GRILL",
        "SCATTERBUSH",
        "THE KEG",
        "MILESTONES",
        "JOEY",
        "JOEY REST",
        "EARLS",
        "CACTUS CLUB",
        "BOSTON PIZZA",
        "EAST SIDE MARIO",
        "RED LOBSTER",
        "OLIVE GARDEN",
        "CHEESecake FACTORY",
        "CHEESECAKE FACTORY",
        "ST LOUIS BAR",
        "WILD WING",
        "BUFFALO WILD",
        "BWW ",
        "DENNY",
        "IHOP",
        "APPLEBEE",
        "CHILI",
        "OUTBACK",
        "RUTH CHRIS",
        "MORTON",
        "RESTAURANT",
        "BISTRO",
        "STEAKHOUSE",
        "SUSHI",
        "RAMEN",
        "POKE",
        "THAI",
        "INDIAN",
        "MEDITERRANEAN",
        "TAPAS",
        "TRATTORIA",
        "TAQUERIA",
        "DINER",
        "GASTROPUB",
        "PUB AND GRILL",
        "GRILL AND BAR",
      ],
    },
    {
      category: "Groceries",
      keywords: [
        "FORTINOS",
        "NO FRILLS",
        "WALMART",
        "WAL-MART",
        "COSTCO",
        "FOOD BASICS",
        "METRO",
        "SOBEYS",
        "LONGOS",
        "FRESHCO",
        "LOBLAWS",
        "REAL CANADIAN SUPERSTORE",
        "SUPERSTORE",
        "T&T",
        "T AND T",
        "FARM BOY",
        "WHOLE FOODS",
        "BULK BARN",
        "NATIONS FRESH",
        "YIG",
        "YOUR INDEPENDENT",
        "ZEHRS",
        "MAXI",
        "PROVIGO",
        "IGA ",
        "CO-OP FOOD",
        "COOP FOOD",
        "FOODLAND",
        "GROCERY",
        "MARKET ",
        "PRODUCE",
        "BUTCHER",
        "BAKERY",
      ],
    },
    {
      category: "Pharmacy",
      keywords: [
        "SHOPPERS DRUG",
        "SHOPPERS DRUG MART",
        "REXALL",
        "PHARMA PLUS",
        "PHARMAPLUS",
        "PHARMACY",
        "GUARDIAN PHARM",
        "IDA PHARM",
        "JEAN COUTU",
        "PHARMAPRIX",
      ],
    },
    {
      category: "Gas",
      keywords: [
        "SHELL",
        "ESSO",
        "PETRO CAN",
        "PETRO-CAN",
        "PIONEER",
        "CIRCLE K",
        "ULTRAMAR",
        "CANADIAN TIRE GAS",
        "HUSKY",
        "MOHAWK",
        "PARKLAND",
        "FUEL",
        "GAS BAR",
        "GAS STATION",
      ],
    },
    {
      category: "Transportation",
      keywords: [
        "UBER TRIP",
        "UBER*TRIP",
        "LYFT",
        "PRESTO",
        "GO TRANSIT",
        "TTC ",
        "TTC-",
        "YRT ",
        "MiWay",
        "VIA RAIL",
        "VIA RAIL CANADA",
        "AIR CANADA",
        "WESTJET",
        "PORTER",
        "PARKING",
        "GREEN P",
        "IMPARK",
        "HONK",
        "PARKING METER",
        "TAXI",
        "CAB ",
      ],
    },
    {
      category: "Travel",
      keywords: [
        "AIRBNB",
        "BOOKING COM",
        "BOOKING.COM",
        "EXPEDIA",
        "HOTELS COM",
        "HOTELS.COM",
        "MARRIOTT",
        "HILTON",
        "HYATT",
        "TRIPADVISOR",
        "TRIVAGO",
        "HOSTEL",
        "RESORT",
      ],
    },
    {
      category: "Shopping",
      keywords: [
        "AMAZON",
        "AMZN",
        "BEST BUY",
        "WINNERS",
        "MARSHALLS",
        "SPORT CHEK",
        "UNIQLO",
        "ZARA",
        "H&M",
        "H AND M",
        "CANADIAN TIRE",
        "HOME DEPOT",
        "LOWES",
        "LOWE'S",
        "IKEA",
        "DOLLARAMA",
        "DOLLAR TREE",
        "INDIGO",
        "CHAPTERS",
        "STAPLES",
        "WALMART.CA",
        "SHEIN",
        "TEMU",
        "ALIEXPRESS",
        "EBAY",
        "ETSY",
        "LULULEMON",
        "ROOTS ",
        "ARITZIA",
        "SIMONS",
        "HUDSON BAY",
        "THE BAY",
        "SAKS",
        "NORDSTROM",
        "GAP ",
        "OLD NAVY",
        "BANANA REPUBLIC",
      ],
    },
    {
      category: "Tech & Apps",
      keywords: [
        "APPLE STORE",
        "APPLE.COM",
        "APPLE COM",
        "GOOGLE PLAY",
        "GOOGLE *",
        "MICROSOFT STORE",
        "STEAMGAMES",
        "STEAM GAMES",
        "EPIC GAMES",
        "BLIZZARD",
        "EA PLAY",
        "SONY INTERACTIV",
        "NINTENDO",
        "XBOX",
        "PLAYSTATION",
        "APP STORE",
        "CURSOR",
        "VERCEL",
        "DIGITALOCEAN",
        "AWS ",
        "AMAZON WEB",
      ],
    },
    {
      category: "Entertainment",
      keywords: [
        "CINEPLEX",
        "FAMOUS PLAYER",
        "LANDMARK CIN",
        "MOVIE",
        "THEATRE",
        "THEATER",
        "TICKETMASTER",
        "LIVE NATION",
        "STUBHUB",
        "SEATGEEK",
        "CONCERT",
        "MUSEUM",
        "GALLERY",
        "ZOO ",
        "AQUARIUM",
        "CN TOWER",
        "RIPLEY",
        "CANADA'S WONDERLAND",
        "WONDERLAND",
        "BOWLING",
        "ESCAPE ROOM",
        "GOLF ",
        "MINI GOLF",
      ],
    },
    {
      category: "Fitness",
      keywords: [
        "GOODLIFE",
        "GOOD LIFE",
        "FIT4LESS",
        "PLANET FITNESS",
        "YMCA",
        "F45",
        "ORANGETHEORY",
        "CROSSFIT",
        "GYM ",
        " FITNESS",
        "PELOTON",
        "CLASSPASS",
      ],
    },
    {
      category: "Health",
      keywords: [
        "DENTIST",
        "DENTAL",
        "DOCTOR",
        "MEDICAL",
        "CLINIC",
        "HOSPITAL",
        "OPTOMETRIST",
        "OPTICAL",
        "PHYSIO",
        "CHIRO",
        "MASSAGE",
        "WELLNESS",
        "THERAPY",
        "PSYCHOLOG",
        "COUNSELL",
      ],
    },
    {
      category: "Personal Care",
      keywords: [
        "SALON",
        "BARBER",
        "HAIR ",
        "NAIL ",
        "SPA ",
        "SEPHORA",
        "BATH AND BODY",
        "BATH & BODY",
        "ULTA",
        "MAC COSMET",
        "COSMETIC",
        "SKINCARE",
      ],
    },
    {
      category: "Pets",
      keywords: [
        "PET SMART",
        "PETSMART",
        "PET VALU",
        "PETVALU",
        "PETLAND",
        "CHEWY",
        "VETERINAR",
        "VET CLINIC",
        "ANIMAL HOSP",
      ],
    },
    {
      category: "Home & Garden",
      keywords: [
        "RONA",
        "HOME HARDWARE",
        "CANADIAN TIRE HOME",
        "BED BATH",
        "BED BATH & BEYOND",
        "LINEN CHEST",
        "WILLIAMS SONOMA",
        "CRATE AND BARREL",
        "STRUCTURE",
        "STRUCTUBE",
        "LEON'S",
        "LEONS",
        "THE BRICK",
        "NURSER",
        "GARDEN CENTRE",
        "GARDEN CENTER",
      ],
    },
    {
      category: "Education",
      keywords: [
        "UNIVERSITY",
        "COLLEGE",
        "TUITION",
        "UDEMY",
        "COURSERA",
        "SKILLSHARE",
        "MASTERCLASS",
        "TEXTBOOK",
        "BOOKSTORE",
        "SCHOOL",
        "ACADEMY",
      ],
    },
    {
      category: "Bills",
      keywords: [
        "HYDRO",
        "ENBRIDGE",
        "TOR HYDRO",
        "ALECTRA",
        "Hydro One",
        "HYDRO ONE",
        "ROGERS CABLE",
        "ROGERS COMM",
        "BELL CANADA",
        "TELUS",
        "SHAW ",
        "COGECO",
        "VIDEOTRON",
        "FIZZ ",
        "INSURANCE",
        "INTACT",
        "TD INSUR",
        "RBC INSUR",
        "UTILITIES",
        "MUNICIPAL",
        "PROPERTY TAX",
      ],
    },
    {
      category: "Rent / Housing",
      keywords: [
        "RENT ",
        "RENTAL",
        "LANDLORD",
        "PROPERTY MGMT",
        "PROPERTY MANAGEMENT",
        "CONDO FEE",
        "STRATA",
        "MORTGAGE",
      ],
    },
  ];

/** Legacy names mapped to current default category names. */
export const LEGACY_CATEGORY_ALIASES: Record<string, string> = {
  "Fast Food": "Fast Food & Delivery",
  "Food Delivery": "Fast Food & Delivery",
};

export const INCOME_KEYWORDS = [
  "PAYROLL",
  "PAYROLL DEPOSIT",
  "DIRECT DEPOSIT",
  "DEPOSIT",
  "EFT DEPOSIT",
  "SALARY",
  "WAGE",
  "PAY CHEQUE",
  "PAYCHEQUE",
  "PAY CHEQ",
  "EMPLOYER",
  "PAYMENT FROM",
  "GOVT OF",
  "GOVERNMENT OF",
  "SERVICE CANADA",
  "EI PAYMENT",
  "INTERAC E-TRANSFER RECEIVED",
  "E-TRANSFER RECEIVED",
  "AUTOMATIC DEPOSIT",
  "MOBILE DEPOSIT",
];

export const SUBSCRIPTION_KEYWORDS =
  CATEGORY_KEYWORD_RULES.find((r) => r.category === "Subscriptions")
    ?.keywords ?? [];

export const TRANSFER_KEYWORDS =
  CATEGORY_KEYWORD_RULES.find((r) => r.category === "Transfers")?.keywords ??
  [];

/** Heuristic patterns when no keyword rule matches (checked in order). */
export const HEURISTIC_CATEGORY_PATTERNS: {
  category: string;
  patterns: RegExp[];
}[] = [
  {
    category: "Fast Food & Delivery",
    patterns: [
      /\b(FIREHOUSE|SUBS|SANDWICH|BURGER|PIZZA|TACO|WING|FRIED CHICKEN)\b/,
      /\b(DRIVE THRU|DRIVE-THRU|TAKEOUT|TAKE OUT)\b/,
    ],
  },
  {
    category: "Restaurants",
    patterns: [
      /\b(GRILL|RESTAURANT|BISTRO|STEAKHOUSE|TAVERN|EATERY|DINER|SUSHI|RAMEN|POKE)\b/,
      /\b(CAFE|CAFÉ)\b/,
    ],
  },
  {
    category: "Coffee",
    patterns: [/\b(COFFEE|ESPRESSO|LATTE|ROASTERY)\b/],
  },
  {
    category: "Groceries",
    patterns: [/\b(GROCERY|SUPERMARKET|MARKET|PRODUCE|BUTCHER)\b/],
  },
  {
    category: "Alcohol & Beverages",
    patterns: [/\b(WINE|LIQUOR|BREW|BEER|CIDER|SPIRITS)\b/],
  },
];
